"""empty message

Revision ID: 2d4396f06af9
Revises: f2e5edaa070f
Create Date: 2017-12-03 22:51:18.117512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4396f06af9'
down_revision = 'f2e5edaa070f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('x_cord', sa.Text(), nullable=True))
    op.add_column('teams', sa.Column('y_cord', sa.Integer(), nullable=True))
    op.drop_column('teams', 'x_cords')
    op.drop_column('teams', 'y_cords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('y_cords', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('x_cords', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'y_cord')
    op.drop_column('teams', 'x_cord')
    # ### end Alembic commands ###
