"""empty message

Revision ID: 56eb7acd857b
Revises: 5ddaee2af470
Create Date: 2017-12-04 09:32:24.936912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eb7acd857b'
down_revision = '5ddaee2af470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'group_id')
    # ### end Alembic commands ###
