"""empty message

Revision ID: 5ddaee2af470
Revises: c831d64c9c1d
Create Date: 2017-12-03 23:22:53.516320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ddaee2af470'
down_revision = 'c831d64c9c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('x_cord', sa.Float(), nullable=True))
    op.drop_column('teams', 'z_cord')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('z_cord', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('teams', 'x_cord')
    # ### end Alembic commands ###
