"""empty message

Revision ID: f2e5edaa070f
Revises: 0fa996478d69
Create Date: 2017-12-03 22:45:05.267104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e5edaa070f'
down_revision = '0fa996478d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('x_cords', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('y_cords', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'y_cords')
    op.drop_column('teams', 'x_cords')
    # ### end Alembic commands ###
