"""empty message

Revision ID: 2d16e0c4af70
Revises: d96e326a357c
Create Date: 2017-08-19 22:41:28.981934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d16e0c4af70'
down_revision = 'd96e326a357c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('host_1_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('host_2_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('host_3_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'teams', ['host_3_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'teams', ['host_2_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'teams', ['host_1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'host_3_id')
    op.drop_column('teams', 'host_2_id')
    op.drop_column('teams', 'host_1_id')
    # ### end Alembic commands ###
