"""empty message

Revision ID: 33569d934ef2
Revises: 873408fe111d
Create Date: 2017-08-23 21:37:32.056668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33569d934ef2'
down_revision = '873408fe111d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('afterparty_time', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'afterparty_time')
    # ### end Alembic commands ###
