"""empty message

Revision ID: 380562164017
Revises: b756a04640b2
Create Date: 2017-12-04 10:05:52.101053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380562164017'
down_revision = 'b756a04640b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_starter_3_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_1_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_3_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_3_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_1_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_1_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_2_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_2_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_2_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_2_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_1_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_3_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_2_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_3_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_1_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_2_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_3_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_3_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_1_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_2_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_1_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_3_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_2_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_1_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_1_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_3_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_2_guest_1_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'teams', ['main_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_3_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_2_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['main_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['main_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['main_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['main_2_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['main_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_2_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['main_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['main_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['starter_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['main_3_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groups', 'teams', ['dessert_3_guest_2'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_main_2_guest_1_fkey', 'groups', 'teams', ['main_2_guest_1'], ['id'])
    op.create_foreign_key('groups_starter_3_host_fkey', 'groups', 'teams', ['starter_3_host'], ['id'])
    op.create_foreign_key('groups_main_1_guest_2_fkey', 'groups', 'teams', ['main_1_guest_2'], ['id'])
    op.create_foreign_key('groups_starter_1_host_fkey', 'groups', 'teams', ['starter_1_host'], ['id'])
    op.create_foreign_key('groups_dessert_2_guest_1_fkey', 'groups', 'teams', ['dessert_2_guest_1'], ['id'])
    op.create_foreign_key('groups_starter_3_guest_2_fkey', 'groups', 'teams', ['starter_3_guest_2'], ['id'])
    op.create_foreign_key('groups_dessert_1_host_fkey', 'groups', 'teams', ['dessert_1_host'], ['id'])
    op.create_foreign_key('groups_starter_2_guest_1_fkey', 'groups', 'teams', ['starter_2_guest_1'], ['id'])
    op.create_foreign_key('groups_dessert_1_guest_2_fkey', 'groups', 'teams', ['dessert_1_guest_2'], ['id'])
    op.create_foreign_key('groups_main_3_guest_2_fkey', 'groups', 'teams', ['main_3_guest_2'], ['id'])
    op.create_foreign_key('groups_dessert_3_guest_1_fkey', 'groups', 'teams', ['dessert_3_guest_1'], ['id'])
    op.create_foreign_key('groups_dessert_2_guest_2_fkey', 'groups', 'teams', ['dessert_2_guest_2'], ['id'])
    op.create_foreign_key('groups_main_1_host_fkey', 'groups', 'teams', ['main_1_host'], ['id'])
    op.create_foreign_key('groups_main_3_host_fkey', 'groups', 'teams', ['main_3_host'], ['id'])
    op.create_foreign_key('groups_dessert_2_host_fkey', 'groups', 'teams', ['dessert_2_host'], ['id'])
    op.create_foreign_key('groups_dessert_3_host_fkey', 'groups', 'teams', ['dessert_3_host'], ['id'])
    op.create_foreign_key('groups_dessert_1_guest_1_fkey', 'groups', 'teams', ['dessert_1_guest_1'], ['id'])
    op.create_foreign_key('groups_starter_2_guest_2_fkey', 'groups', 'teams', ['starter_2_guest_2'], ['id'])
    op.create_foreign_key('groups_main_2_host_fkey', 'groups', 'teams', ['main_2_host'], ['id'])
    op.create_foreign_key('groups_main_2_guest_2_fkey', 'groups', 'teams', ['main_2_guest_2'], ['id'])
    op.create_foreign_key('groups_starter_2_host_fkey', 'groups', 'teams', ['starter_2_host'], ['id'])
    op.create_foreign_key('groups_starter_1_guest_1_fkey', 'groups', 'teams', ['starter_1_guest_1'], ['id'])
    op.create_foreign_key('groups_main_1_guest_1_fkey', 'groups', 'teams', ['main_1_guest_1'], ['id'])
    op.create_foreign_key('groups_main_3_guest_1_fkey', 'groups', 'teams', ['main_3_guest_1'], ['id'])
    op.create_foreign_key('groups_dessert_3_guest_2_fkey', 'groups', 'teams', ['dessert_3_guest_2'], ['id'])
    op.create_foreign_key('groups_starter_1_guest_2_fkey', 'groups', 'teams', ['starter_1_guest_2'], ['id'])
    op.create_foreign_key('groups_starter_3_guest_1_fkey', 'groups', 'teams', ['starter_3_guest_1'], ['id'])
    # ### end Alembic commands ###
