"""empty message

Revision ID: 5a673b0db2f2
Revises: 380562164017
Create Date: 2017-12-04 10:21:12.732993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a673b0db2f2'
down_revision = '380562164017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_dessert_3_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_2_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_1_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_3_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_2_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_1_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_3_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_3_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_1_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_3_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_3_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_2_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_1_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_1_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_1_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_3_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_2_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_1_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_3_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_1_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_3_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_2_guest_1_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_dessert_2_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_1_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_2_host_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_main_2_guest_2_fkey', 'groups', type_='foreignkey')
    op.drop_constraint('groups_starter_2_guest_1_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key('5', 'groups', 'teams', ['starter_2_guest_1'], ['id'])
    op.create_foreign_key('11', 'groups', 'teams', ['main_1_guest_1'], ['id'])
    op.create_foreign_key('17', 'groups', 'teams', ['main_3_guest_1'], ['id'])
    op.create_foreign_key('24', 'groups', 'teams', ['dessert_2_guest_2'], ['id'])
    op.create_foreign_key('23', 'groups', 'teams', ['dessert_2_guest_1'], ['id'])
    op.create_foreign_key('25', 'groups', 'teams', ['dessert_3_host'], ['id'])
    op.create_foreign_key('22', 'groups', 'teams', ['dessert_2_host'], ['id'])
    op.create_foreign_key('8', 'groups', 'teams', ['starter_3_guest_1'], ['id'])
    op.create_foreign_key('12', 'groups', 'teams', ['main_1_guest_2'], ['id'])
    op.create_foreign_key('18', 'groups', 'teams', ['main_3_guest_2'], ['id'])
    op.create_foreign_key('10', 'groups', 'teams', ['main_1_host'], ['id'])
    op.create_foreign_key('6', 'groups', 'teams', ['starter_2_guest_2'], ['id'])
    op.create_foreign_key('1', 'groups', 'teams', ['starter_1_host'], ['id'])
    op.create_foreign_key('4', 'groups', 'teams', ['starter_2_host'], ['id'])
    op.create_foreign_key('20', 'groups', 'teams', ['dessert_1_guest_1'], ['id'])
    op.create_foreign_key('27', 'groups', 'teams', ['dessert_3_guest_2'], ['id'])
    op.create_foreign_key('13', 'groups', 'teams', ['main_2_host'], ['id'])
    op.create_foreign_key('7', 'groups', 'teams', ['starter_3_host'], ['id'])
    op.create_foreign_key('15', 'groups', 'teams', ['main_2_guest_2'], ['id'])
    op.create_foreign_key('19', 'groups', 'teams', ['dessert_1_host'], ['id'])
    op.create_foreign_key('16', 'groups', 'teams', ['main_3_host'], ['id'])
    op.create_foreign_key('9', 'groups', 'teams', ['starter_3_guest_2'], ['id'])
    op.create_foreign_key('3', 'groups', 'teams', ['starter_1_guest_2'], ['id'])
    op.create_foreign_key('2', 'groups', 'teams', ['starter_1_guest_1'], ['id'])
    op.create_foreign_key('21', 'groups', 'teams', ['dessert_1_guest_2'], ['id'])
    op.create_foreign_key('26', 'groups', 'teams', ['dessert_3_guest_1'], ['id'])
    op.create_foreign_key('14', 'groups', 'teams', ['main_2_guest_1'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('14', 'groups', type_='foreignkey')
    op.drop_constraint('26', 'groups', type_='foreignkey')
    op.drop_constraint('21', 'groups', type_='foreignkey')
    op.drop_constraint('2', 'groups', type_='foreignkey')
    op.drop_constraint('3', 'groups', type_='foreignkey')
    op.drop_constraint('9', 'groups', type_='foreignkey')
    op.drop_constraint('16', 'groups', type_='foreignkey')
    op.drop_constraint('19', 'groups', type_='foreignkey')
    op.drop_constraint('15', 'groups', type_='foreignkey')
    op.drop_constraint('7', 'groups', type_='foreignkey')
    op.drop_constraint('13', 'groups', type_='foreignkey')
    op.drop_constraint('27', 'groups', type_='foreignkey')
    op.drop_constraint('20', 'groups', type_='foreignkey')
    op.drop_constraint('4', 'groups', type_='foreignkey')
    op.drop_constraint('1', 'groups', type_='foreignkey')
    op.drop_constraint('6', 'groups', type_='foreignkey')
    op.drop_constraint('10', 'groups', type_='foreignkey')
    op.drop_constraint('18', 'groups', type_='foreignkey')
    op.drop_constraint('12', 'groups', type_='foreignkey')
    op.drop_constraint('8', 'groups', type_='foreignkey')
    op.drop_constraint('22', 'groups', type_='foreignkey')
    op.drop_constraint('25', 'groups', type_='foreignkey')
    op.drop_constraint('23', 'groups', type_='foreignkey')
    op.drop_constraint('24', 'groups', type_='foreignkey')
    op.drop_constraint('17', 'groups', type_='foreignkey')
    op.drop_constraint('11', 'groups', type_='foreignkey')
    op.drop_constraint('5', 'groups', type_='foreignkey')
    op.create_foreign_key('groups_starter_2_guest_1_fkey', 'groups', 'teams', ['starter_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_2_guest_2_fkey', 'groups', 'teams', ['main_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_2_host_fkey', 'groups', 'teams', ['main_2_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_1_guest_2_fkey', 'groups', 'teams', ['main_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_2_host_fkey', 'groups', 'teams', ['dessert_2_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_2_guest_1_fkey', 'groups', 'teams', ['dessert_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_starter_3_guest_1_fkey', 'groups', 'teams', ['starter_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_1_guest_1_fkey', 'groups', 'teams', ['main_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_3_guest_2_fkey', 'groups', 'teams', ['main_3_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_starter_1_guest_1_fkey', 'groups', 'teams', ['starter_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_starter_2_host_fkey', 'groups', 'teams', ['starter_2_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_3_guest_1_fkey', 'groups', 'teams', ['dessert_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_starter_1_host_fkey', 'groups', 'teams', ['starter_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_1_guest_2_fkey', 'groups', 'teams', ['dessert_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_1_guest_1_fkey', 'groups', 'teams', ['dessert_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_2_guest_2_fkey', 'groups', 'teams', ['dessert_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_starter_3_host_fkey', 'groups', 'teams', ['starter_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_3_guest_1_fkey', 'groups', 'teams', ['main_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_1_host_fkey', 'groups', 'teams', ['dessert_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_3_host_fkey', 'groups', 'teams', ['dessert_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_3_host_fkey', 'groups', 'teams', ['main_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_1_host_fkey', 'groups', 'teams', ['main_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_starter_2_guest_2_fkey', 'groups', 'teams', ['starter_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_starter_3_guest_2_fkey', 'groups', 'teams', ['starter_3_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_starter_1_guest_2_fkey', 'groups', 'teams', ['starter_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_main_2_guest_1_fkey', 'groups', 'teams', ['main_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('groups_dessert_3_guest_2_fkey', 'groups', 'teams', ['dessert_3_guest_2'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
