"""empty message

Revision ID: 631cbe926fce
Revises: 9f9123c68302
Create Date: 2017-06-05 21:33:29.290155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631cbe926fce'
down_revision = '9f9123c68302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participants_team_id_fkey', 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key('participants_team_id_fkey', 'participants', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
