"""empty message

Revision ID: 69f8b61d8c18
Revises: 78a7c4eeefad
Create Date: 2017-12-04 22:46:32.750312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f8b61d8c18'
down_revision = '78a7c4eeefad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('22', 'groups', type_='foreignkey')
    op.drop_constraint('23', 'groups', type_='foreignkey')
    op.create_foreign_key('23', 'groups', 'teams', ['dessert_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('22', 'groups', 'teams', ['dessert_2_host'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('22', 'groups', type_='foreignkey')
    op.drop_constraint('23', 'groups', type_='foreignkey')
    op.create_foreign_key('23', 'groups', 'teams', ['dessert_2_guest_1'], ['id'])
    op.create_foreign_key('22', 'groups', 'teams', ['dessert_2_host'], ['id'])
    # ### end Alembic commands ###
