"""empty message

Revision ID: 78a7c4eeefad
Revises: 4b55e5cd53f0
Create Date: 2017-12-04 22:43:15.518851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a7c4eeefad'
down_revision = '4b55e5cd53f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('12', 'groups', type_='foreignkey')
    op.drop_constraint('5', 'groups', type_='foreignkey')
    op.drop_constraint('27', 'groups', type_='foreignkey')
    op.drop_constraint('4', 'groups', type_='foreignkey')
    op.drop_constraint('11', 'groups', type_='foreignkey')
    op.drop_constraint('18', 'groups', type_='foreignkey')
    op.drop_constraint('7', 'groups', type_='foreignkey')
    op.drop_constraint('13', 'groups', type_='foreignkey')
    op.drop_constraint('19', 'groups', type_='foreignkey')
    op.drop_constraint('10', 'groups', type_='foreignkey')
    op.drop_constraint('15', 'groups', type_='foreignkey')
    op.drop_constraint('25', 'groups', type_='foreignkey')
    op.drop_constraint('20', 'groups', type_='foreignkey')
    op.drop_constraint('3', 'groups', type_='foreignkey')
    op.drop_constraint('1', 'groups', type_='foreignkey')
    op.drop_constraint('2', 'groups', type_='foreignkey')
    op.drop_constraint('9', 'groups', type_='foreignkey')
    op.drop_constraint('17', 'groups', type_='foreignkey')
    op.drop_constraint('24', 'groups', type_='foreignkey')
    op.drop_constraint('14', 'groups', type_='foreignkey')
    op.drop_constraint('16', 'groups', type_='foreignkey')
    op.drop_constraint('6', 'groups', type_='foreignkey')
    op.drop_constraint('21', 'groups', type_='foreignkey')
    op.drop_constraint('8', 'groups', type_='foreignkey')
    op.drop_constraint('26', 'groups', type_='foreignkey')
    op.create_foreign_key('2', 'groups', 'teams', ['starter_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('5', 'groups', 'teams', ['starter_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('1', 'groups', 'teams', ['starter_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('17', 'groups', 'teams', ['main_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('8', 'groups', 'teams', ['starter_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('13', 'groups', 'teams', ['main_2_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('7', 'groups', 'teams', ['starter_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('15', 'groups', 'teams', ['main_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('11', 'groups', 'teams', ['main_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('10', 'groups', 'teams', ['main_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('19', 'groups', 'teams', ['dessert_1_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('20', 'groups', 'teams', ['dessert_1_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('14', 'groups', 'teams', ['main_2_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('25', 'groups', 'teams', ['dessert_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('12', 'groups', 'teams', ['main_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('4', 'groups', 'teams', ['starter_2_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('24', 'groups', 'teams', ['dessert_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('27', 'groups', 'teams', ['dessert_3_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('16', 'groups', 'teams', ['main_3_host'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('26', 'groups', 'teams', ['dessert_3_guest_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('21', 'groups', 'teams', ['dessert_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('18', 'groups', 'teams', ['main_3_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('6', 'groups', 'teams', ['starter_2_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('3', 'groups', 'teams', ['starter_1_guest_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('9', 'groups', 'teams', ['starter_3_guest_2'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('9', 'groups', type_='foreignkey')
    op.drop_constraint('3', 'groups', type_='foreignkey')
    op.drop_constraint('6', 'groups', type_='foreignkey')
    op.drop_constraint('18', 'groups', type_='foreignkey')
    op.drop_constraint('21', 'groups', type_='foreignkey')
    op.drop_constraint('26', 'groups', type_='foreignkey')
    op.drop_constraint('16', 'groups', type_='foreignkey')
    op.drop_constraint('27', 'groups', type_='foreignkey')
    op.drop_constraint('24', 'groups', type_='foreignkey')
    op.drop_constraint('4', 'groups', type_='foreignkey')
    op.drop_constraint('12', 'groups', type_='foreignkey')
    op.drop_constraint('25', 'groups', type_='foreignkey')
    op.drop_constraint('14', 'groups', type_='foreignkey')
    op.drop_constraint('20', 'groups', type_='foreignkey')
    op.drop_constraint('19', 'groups', type_='foreignkey')
    op.drop_constraint('10', 'groups', type_='foreignkey')
    op.drop_constraint('11', 'groups', type_='foreignkey')
    op.drop_constraint('15', 'groups', type_='foreignkey')
    op.drop_constraint('7', 'groups', type_='foreignkey')
    op.drop_constraint('13', 'groups', type_='foreignkey')
    op.drop_constraint('8', 'groups', type_='foreignkey')
    op.drop_constraint('17', 'groups', type_='foreignkey')
    op.drop_constraint('1', 'groups', type_='foreignkey')
    op.drop_constraint('5', 'groups', type_='foreignkey')
    op.drop_constraint('2', 'groups', type_='foreignkey')
    op.create_foreign_key('26', 'groups', 'teams', ['dessert_3_guest_1'], ['id'])
    op.create_foreign_key('8', 'groups', 'teams', ['starter_3_guest_1'], ['id'])
    op.create_foreign_key('21', 'groups', 'teams', ['dessert_1_guest_2'], ['id'])
    op.create_foreign_key('6', 'groups', 'teams', ['starter_2_guest_2'], ['id'])
    op.create_foreign_key('16', 'groups', 'teams', ['main_3_host'], ['id'])
    op.create_foreign_key('14', 'groups', 'teams', ['main_2_guest_1'], ['id'])
    op.create_foreign_key('24', 'groups', 'teams', ['dessert_2_guest_2'], ['id'])
    op.create_foreign_key('17', 'groups', 'teams', ['main_3_guest_1'], ['id'])
    op.create_foreign_key('9', 'groups', 'teams', ['starter_3_guest_2'], ['id'])
    op.create_foreign_key('2', 'groups', 'teams', ['starter_1_guest_1'], ['id'])
    op.create_foreign_key('1', 'groups', 'teams', ['starter_1_host'], ['id'])
    op.create_foreign_key('3', 'groups', 'teams', ['starter_1_guest_2'], ['id'])
    op.create_foreign_key('20', 'groups', 'teams', ['dessert_1_guest_1'], ['id'])
    op.create_foreign_key('25', 'groups', 'teams', ['dessert_3_host'], ['id'])
    op.create_foreign_key('15', 'groups', 'teams', ['main_2_guest_2'], ['id'])
    op.create_foreign_key('10', 'groups', 'teams', ['main_1_host'], ['id'])
    op.create_foreign_key('19', 'groups', 'teams', ['dessert_1_host'], ['id'])
    op.create_foreign_key('13', 'groups', 'teams', ['main_2_host'], ['id'])
    op.create_foreign_key('7', 'groups', 'teams', ['starter_3_host'], ['id'])
    op.create_foreign_key('18', 'groups', 'teams', ['main_3_guest_2'], ['id'])
    op.create_foreign_key('11', 'groups', 'teams', ['main_1_guest_1'], ['id'])
    op.create_foreign_key('4', 'groups', 'teams', ['starter_2_host'], ['id'])
    op.create_foreign_key('27', 'groups', 'teams', ['dessert_3_guest_2'], ['id'])
    op.create_foreign_key('5', 'groups', 'teams', ['starter_2_guest_1'], ['id'])
    op.create_foreign_key('12', 'groups', 'teams', ['main_1_guest_2'], ['id'])
    # ### end Alembic commands ###
