"""empty message

Revision ID: 7969016dbc50
Revises: 631cbe926fce
Create Date: 2017-06-05 23:30:12.876830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7969016dbc50'
down_revision = '631cbe926fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('starter_1_id', sa.Integer(), nullable=True),
    sa.Column('starter_2_id', sa.Integer(), nullable=True),
    sa.Column('starter_3_id', sa.Integer(), nullable=True),
    sa.Column('main_1_id', sa.Integer(), nullable=True),
    sa.Column('main_2_id', sa.Integer(), nullable=True),
    sa.Column('main_3_id', sa.Integer(), nullable=True),
    sa.Column('dessert_1_id', sa.Integer(), nullable=True),
    sa.Column('dessert_2_id', sa.Integer(), nullable=True),
    sa.Column('dessert_3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dessert_1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['dessert_2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['dessert_3_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['main_1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['main_2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['main_3_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['starter_1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['starter_2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['starter_3_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'events', ['subdomain'])
    op.add_column('teams', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'group_id')
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_table('groups')
    # ### end Alembic commands ###
