"""empty message

Revision ID: 873408fe111d
Revises: ee8db6944399
Create Date: 2017-08-19 23:16:05.887492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873408fe111d'
down_revision = 'ee8db6944399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('events', 'status2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
