"""empty message

Revision ID: 98e60820e80a
Revises: 0a7f81986e5c
Create Date: 2017-06-03 23:38:00.100334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e60820e80a'
down_revision = '0a7f81986e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
