"""empty message

Revision ID: 9f9123c68302
Revises: c1b895fab16d
Create Date: 2017-06-05 14:44:49.459510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9123c68302'
down_revision = 'c1b895fab16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participants_email', table_name='participants')
    op.create_index(op.f('ix_participants_email'), 'participants', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_email'), table_name='participants')
    op.create_index('ix_participants_email', 'participants', ['email'], unique=True)
    # ### end Alembic commands ###
