"""empty message

Revision ID: b756a04640b2
Revises: 33569d934ef2
Create Date: 2017-12-04 10:02:38.622189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b756a04640b2'
down_revision = '33569d934ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('x_cord', sa.Float(), nullable=True))
    op.add_column('teams', sa.Column('y_cord', sa.Float(), nullable=True))
    op.drop_constraint('teams_group_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_group_id_fkey', 'teams', 'groups', ['group_id'], ['id'])
    op.drop_column('teams', 'y_cord')
    op.drop_column('teams', 'x_cord')
    # ### end Alembic commands ###
