"""empty message

Revision ID: c1b895fab16d
Revises: 98e60820e80a
Create Date: 2017-06-04 09:40:22.625043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b895fab16d'
down_revision = '98e60820e80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('subdomain', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'subdomain')
    # ### end Alembic commands ###
